version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal_password
    networks:
      - drupal

  drupal:
    build: ./drupal
    container_name: drupal
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - drupal
    environment:
      DRUPAL_DATABASE_HOST: postgres
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal_password

networks:
  drupal:
    driver: bridge

